### ISSUE TITLE
end-to-end test fails - failed to pull image

### ISSUE THREAD

**Issue by giulioroggero** [kube-green/kube-green#153]
Hi there!

I'm trying to run the end to end test

`kubectl kuttl test --skip-cluster-delete`

on my mac book with podman and kind but it fails because the image `kubegreen/kube-green:e2e-test` is not found. Please find below the events of the controller `kube-green-controller-manager`

```sh
Events:
  Type     Reason          Age                    From     Message
  ----     ------          ----                   ----     -------
  Normal   BackOff         9d (x6507 over 10d)    kubelet  Back-off pulling image "kubegreen/kube-green:e2e-test"
  Warning  FailedMount     27m                    kubelet  MountVolume.SetUp failed for volume "cert" : failed to sync secret cache: timed out waiting for the condition
  Normal   SandboxChanged  27m                    kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          27m                    kubelet  Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.12.0" already present on machine
  Normal   Created         27m                    kubelet  Created container kube-rbac-proxy
  Normal   Started         27m                    kubelet  Started container kube-rbac-proxy
  Normal   Pulling         27m (x3 over 27m)      kubelet  Pulling image "kubegreen/kube-green:e2e-test"
  Warning  Failed          26m (x3 over 27m)      kubelet  Failed to pull image "kubegreen/kube-green:e2e-test": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/kubegreen/kube-green:e2e-test": failed to resolve reference "docker.io/kubegreen/kube-green:e2e-test": docker.io/kubegreen/kube-green:e2e-test: not found
  Warning  Failed          26m (x3 over 27m)      kubelet  Error: ErrImagePull
  Warning  Failed          26m (x5 over 27m)      kubelet  Error: ImagePullBackOff
  Normal   BackOff         2m33s (x109 over 27m)  kubelet  Back-off pulling image "kubegreen/kube-green:e2e-test"
``` 

I check on https://hub.docker.com/u/kubegreen and the image is not available.

**Comment by davidebianchi** [comment]
Hi @giulioroggero! 

Have you tried to follow [the README section](https://github.com/kube-green/kube-green#running-the-tests) to run the tests?
The `kubegreen/kube-green:e2e-test` should be built locally (using the `make docker-test-build` command), in order to try the last changes and after that load the image into `kind`. It is intended to don't be on the docker registry, to avoid to test with a incorrect version of the image, already on the registry and without current modification. 
Keep attention: _kind_ at the moment does not support the load of the image if you are using podman (see issue [here](https://github.com/kubernetes-sigs/kind/issues/2038)).

If you want to test the latest official image, you can:

* change [this line](https://github.com/kube-green/kube-green/blob/main/kuttl-test.yaml#L11) with:
	```yaml
	  - command: kubectl kustomize $PWD/config/default/ -o /tmp/kube-green-test.yaml
	```
	and this will use the last tagged kube-green image;
* or, alternatively, change the [newTag field here](https://github.com/kube-green/kube-green/blob/main/config/e2e-test/kustomization.yaml#L9) and set a kube-green already existent version, like `latest`.

**Comment by giulioroggero** [comment]
Hi @davidebianchi , 
I'm using podman+kind on Mac. This is why it doesn't work...
I try to figure out an alternative

**Comment by davidebianchi** [comment]
I close this issue since it is not related to kube-green.

Some possible solution are:
* use kind with docker until kind does not add full support to docker;
* use the suggestion I write in the above comment, with a custom docker image pushed in an online docker registry if you want to test your changes

If you need some other help, please reopen the issue.
