### ISSUE TITLE
Stop nodes

### ISSUE THREAD

**Issue by GoranHalvarsson** [kube-green/kube-green#299]
Is it possible to Stop nodes too?

Say we want to stop nodes during nights. Is it possible from kube-green?

**Comment by davidebianchi** [comment]
It's not possible directly. It is however possible to stop nodes automatically if the cluster autoscaler is enabled in your cluster. This happen because kube-green stop the workload, so nodes have low utilization and the autoscaler scale down the nodes.
[Here](https://kube-green.dev/docs/FAQ/#i-have-a-couple-of-nodes-with-low-utilization-but-they-are-not-scaled-down-why) there is a FAQ if nodes does not downscale, and [here](https://kube-green.dev/docs/real-usecase/node-downscale/) an use case which shows the downscale of the cluster.
Could this be useful for your use case?

**Comment by Frankkkkk** [comment]
I'm currently working on an operator that exclusively does the stop/start of the (bare metal) nodes. Still a WIP but I think it would be a nice complement to kube-green :-)

**Comment by davidebianchi** [comment]
Close this, since it is done by kube-green indirectly and it is not in scope to address it directly. Reopen it if needed!
