### ISSUE TITLE
How does kube-green perform shutdown and restarts?

### ISSUE THREAD

**Issue by faizanbashir** [kube-green/kube-green#305]
I am exploring kube-green for our setup and I have a few questions:

1. Can we scale down the entire workloads in namespace or do we have have to do it per workload?
2. Can it be used to delete HPA and Keda ScaledObjects? (The reason for asking this question is that we have HPAs and ScaledObjects on deployments, if we scale the deployment to 0 they will restart the pod)
3. Can we scale down openshift deploymentconfigs?
4. If we have to perform bulk shutdown of lets say 100+ namespaces and want to prioritise starting up statefulsets before deployments can we do it?
5. Can we pull the records of the shutdown, startups done in the past 3 months?
6. How are the startups performed? Does kube-green spin up cronjobs to shutdown/startup for individual deployments or does it perform bulk if there are a lot of workloads?

**Comment by davidebianchi** [comment]
Hi @faizanbashir! I try to answer to your questions.

1. The downscale if per workload type, at the moment we support Deployment and CronJob but we would like to add more resources. All workload of this kind will be stopped, if not excluded by the `ExcludeRef` field in the `SleepInfo` CRD
2. Not at the moment, but we want to support to stop also the CRD. For the HPA, if you set to 0 it does upscale the resource? Because I remember that it does not change if value is 0, but I could misremember
3. Not at the moment, same answer as above
4. It's possible if the resources are in some specific namespaces, which can be set with to wake up before other namespaces. Howewer `StatefulSets` are not supported at the moment.
5. At the moment only the last startup/shutdown is recorded. It could be interesting to add some history (we want also to support more prometheus metrics info)
6. Startups are for namespaces, not for individual deployments. At the moment it is managed by the operator itself.

**Comment by faizanbashir** [comment]
@davidebianchi - Thanks for your response. At the start of this year, I faced the need to perform shutdowns on close to ~5000 pods every weekend. Before building the system, I briefly searched for an OS solution but found none. Out of interest, I came across kube-green and wanted to see if it could support our use case.
